list: $/thulana/portfolio/models/comment/columns.yaml
modelClass: Thulana\Portfolio\Models\Comment
title: Comments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'thulana/portfolio/comments/update/:id'
