list: $/thulana/portfolio/models/project/columns.yaml
modelClass: Thulana\Portfolio\Models\Project
title: Projects
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'thulana/portfolio/projects/update/:id'
